#!/bin/sh
# memory-view.sh — open THIS store's memory viewer.
#
# ON WINDOWS, USE memory-view.cmd INSTEAD. A .sh file has no execute
# association there, so clicking this one only ever offers to OPEN it in an
# editor — that is Windows working as intended, not a broken launcher. This
# file is for Linux and macOS, where it is tracked with its execute bit set so
# a fresh clone can run it without chmod.
#
# Run it (or double-click where your desktop allows). It refreshes this
# repository's own map, starts the viewer for THIS store only, and opens a
# browser on it.
#
# WHY A SERVER AND NOT JUST THE HTML: graph-view.html beside this file is a
# SNAPSHOT. A page opened straight off disk is a file:// page, and browsers
# forbid a file:// page from reading local files — it can neither re-read
# nodes.jsonl nor run `git log`, so it shows the repository as it stood when it
# was rendered. Served over loopback, the same page is rebuilt from the logs and
# from `git log` on every request, and refreshes itself when they change.
#
# IT CLEANS UP AFTER ITSELF: closing the last viewer tab stops the server.
# IT SHARES THE MACHINE: it takes the first free port from 8765 upward, so other
# local viewers can hold 8765, and a second launch reuses a running one.
#
# GENERATED by `memory_views.py install`. Wired to the store beside it.
set -e
STORE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO=$(CDPATH= cd -- "$STORE/.." && pwd)

C="$REPO"
found=
for _ in 1 2 3 4; do
    C=$(dirname "$C")
    if [ -f "$C/scripts/memory_views.py" ]; then found=yes; break; fi
done
if [ -z "$found" ]; then
    echo "memory-view: could not find scripts/memory_views.py above $STORE." >&2
    echo "memory-view: this store's viewer is served by the orchestration" >&2
    echo "memory-view: container that sits above this repository. Without it" >&2
    echo "memory-view: there is still a rendered snapshot beside this file:" >&2
    echo "memory-view:   $STORE/graph-view.html" >&2
    exit 2
fi

# Pick an interpreter by RUNNING it, never by `command -v`. On Windows,
# `python3` resolves to the Microsoft Store alias stub — a real file on PATH
# that is not Python: it prints "no Python found, install from the Store" and
# exits. `command -v` says yes, execution says no, and only the second answer
# is worth anything. `py -3` is tried first because it is the launcher that is
# actually correct on Windows.
PY=
for cand in "py -3" python3 python; do
    if $cand -c "import sys; sys.exit(0)" >/dev/null 2>&1; then PY="$cand"; break; fi
done
if [ -z "$PY" ]; then
    echo "memory-view: no working Python found (tried: py -3, python3, python)." >&2
    echo "memory-view: the rendered snapshot is still readable beside this file:" >&2
    echo "memory-view:   $STORE/graph-view.html" >&2
    exit 2
fi

$PY "$C/scripts/memory_graph.py" refresh --store "$STORE" --root "$REPO" >/dev/null 2>&1 || true
exec $PY "$C/scripts/memory_views.py" serve --store "$STORE" --open-browser "$@"
