@echo off
REM memory-view.cmd - open THIS store's memory viewer.
REM
REM THIS is the file to click on Windows. memory-view.sh beside it is the same
REM launcher for Linux and macOS; Windows has no execute association for .sh,
REM so clicking that one only offers to open it in an editor.
REM
REM WHY A SERVER AND NOT JUST THE HTML: graph-view.html beside this file is a
REM BOOTSTRAP. It holds no records. A page opened straight off disk is a
REM file:// page, and browsers forbid those from reading local files, so it
REM cannot read the JSONL logs or run `git log`. Served over loopback, the same page is rebuilt on
REM every request and reloads itself when its source changes.
REM
REM IT CLEANS UP AFTER ITSELF: closing the last viewer tab stops the server.
REM IT KEEPS TO ITSELF: its port is derived from this store's own path,
REM it serves only this one, and it never looks for or talks to another.
REM
REM GENERATED by `memory_views.py install`. Wired to the store beside it.
setlocal EnableDelayedExpansion
set "HERE=%~dp0"
set "HERE=%HERE:~0,-1%"

REM Pick an interpreter by RUNNING it, never by asking `where`: `python` on
REM Windows may be the Microsoft Store ALIAS STUB, a real file on PATH that is
REM not Python. It prints an advert and exits. `where` says yes and execution
REM says no, and only the second answer is worth having.
set "PY="
py -3 -c "import sys" >nul 2>&1 && set "PY=py -3"
if not defined PY python -c "import sys" >nul 2>&1 && set "PY=python"
if not defined PY (
  echo memory-view: no working Python found ^(tried: py -3, python^).
  echo memory-view: graph-view.html beside this file is a BOOTSTRAP and holds no
  echo memory-view: records: it fills itself from this viewer once the viewer
  echo memory-view: runs. Without Python there is nothing to read yet.
  pause
  exit /b 2
)

if not exist "%HERE%\memory_views.py" (
  echo memory-view: memory_views.py is not beside this launcher.
  echo memory-view: this store carries its own viewer so the repository
  echo memory-view: works when cloned alone; without it there is nothing to
  echo memory-view: serve. Restore it with:
  echo memory-view:   memory_views.py install --store "%HERE%"
  echo memory-view: run from a tree that still has one.
  pause
  exit /b 2
)
REM Refresh this store before serving it, WHEN AN ENGINE IS
REM REACHABLE: the store itself first, so a genuinely
REM self-contained store wins, then a BOUNDED five-level walk UP
REM for an orchestration scripts\ folder. A fixed ..\.. would be
REM right only where the product sits directly at
REM <container>\main; one level deeper it misses in silence.
set "ENGINE="
if exist "%HERE%\memory_graph.py" set "ENGINE=%HERE%\memory_graph.py"
if not defined ENGINE (
  set "C=%HERE%"
  for %%L in (1 2 3 4 5) do (
    for %%D in ("!C!\..") do set "C=%%~fD"
    if not defined ENGINE if exist "!C!\scripts\memory_graph.py" set "ENGINE=!C!\scripts\memory_graph.py"
  )
)
if defined ENGINE (
  %PY% "!ENGINE!" refresh --store "%HERE%" --root "%HERE%\.." >nul 2>&1
) else (
  REM An unrefreshed map served in silence is believed. Say so.
  %PY% "%HERE%\memory_views.py" engine-missing --store "%HERE%" 1>&2
)
%PY% "%HERE%\memory_views.py" serve --store "%HERE%" --open-browser %*
REM A .cmd double-clicked from Explorer closes its window the instant the
REM script ends, so a named exit nobody can read is the same as no message at
REM all. This is where the exhausted-port-block message lands.
if errorlevel 1 pause
endlocal
