@echo off
REM memory-view.cmd - open THIS store's memory viewer.
REM
REM THIS is the file to click on Windows. memory-view.sh beside it is the same
REM launcher for Linux and macOS; Windows has no execute association for .sh,
REM so clicking that one only offers to open it in an editor.
REM
REM Double-click it. It refreshes this repository's own map, starts the viewer
REM for THIS store only, and opens a browser on it.
REM
REM WHY A SERVER AND NOT JUST THE HTML: graph-view.html beside this file is a
REM SNAPSHOT. A page opened straight off disk is a file:// page, and browsers
REM forbid a file:// page from reading local files -- it can neither re-read
REM nodes.jsonl nor run `git log`, so it shows the repository as it stood when
REM it was rendered. Served over loopback, the same page is rebuilt from the
REM logs and from `git log` on every request, and refreshes itself when they
REM change.
REM
REM IT CLEANS UP AFTER ITSELF: closing the last viewer tab stops the server.
REM IT SHARES THE MACHINE: it takes the first free port from 8765 upward, so
REM other local viewers can hold 8765, and a second launch reuses a running one.
REM
REM GENERATED by `memory_views.py install`. Wired to the store beside it.

REM DELAYED EXPANSION IS REQUIRED, not stylistic. `%C%` inside a parenthesised
REM block is substituted ONCE, when the block is PARSED, so a walk written with
REM it tests the same directory on every pass and never climbs. That bug was
REM invisible from the container -- whose store sits one level below it, so the
REM first test succeeded -- and fatal from every product store, where the first
REM test lands on the repository's own scripts\ directory, which has no
REM memory_views.py. `!C!` is substituted per pass, which is the whole point.
setlocal EnableDelayedExpansion
set "STORE=%~dp0"
set "STORE=%STORE:~0,-1%"

REM Walk up for the container that holds the viewer implementation.
set "C=%STORE%\.."
for /L %%i in (1,1,4) do (
  if exist "!C!\scripts\memory_views.py" goto :found
  set "C=!C!\.."
)
echo memory-view: could not find scripts\memory_views.py above "%STORE%".
echo memory-view: this store's viewer is served by the orchestration container
echo memory-view: that sits above this repository. Without it there is no
echo memory-view: viewer to serve this store, and graph-view.html beside this
echo memory-view: file will stay empty -- it is a TEMPLATE that fills itself
echo memory-view: from a running viewer and holds no records of its own.
pause
exit /b 2

:found
REM Pick an interpreter by RUNNING it. On Windows `python` may be the Microsoft
REM Store alias stub -- a real file on PATH that is not Python: it prints an
REM install advert and exits. `where` says yes, execution says no, and only the
REM second answer is worth anything.
set "PY="
py -3 -c "import sys" >nul 2>&1 && set "PY=py -3"
if not defined PY python -c "import sys" >nul 2>&1 && set "PY=python"
if not defined PY (
  echo memory-view: no working Python found ^(tried: py -3, python^).
  echo memory-view: graph-view.html beside this file is a TEMPLATE and holds
  echo memory-view: no records: it fills itself from this viewer once the
  echo memory-view: viewer runs. Without Python there is nothing to read yet:
  echo memory-view:   %STORE%\graph-view.html
  pause
  exit /b 2
)
%PY% "%C%\scripts\memory_graph.py" refresh --store "%STORE%" --root "%STORE%\.." >nul 2>&1
%PY% "%C%\scripts\memory_views.py" serve --store "%STORE%" --open-browser %*
