#!/bin/sh
# memory-view.sh - open THIS store's memory viewer.
#
# The same launcher as memory-view.cmd, for Linux and macOS.
#
# WHY A SERVER AND NOT JUST THE HTML: graph-view.html beside this file is a BOOTSTRAP.
# It holds no records. A page opened straight off disk is a file:// page, and
# browsers forbid those from reading local files, so it cannot read the JSONL logs or run `git log`.
#
# IT CLEANS UP AFTER ITSELF: closing the last viewer tab stops the server.
# IT KEEPS TO ITSELF: its port is derived from this store's own path, it
# serves only this one, and it never looks for or talks to another.
#
# GENERATED by `memory_views.py install`. Wired to the store beside it.
set -eu
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# Shortlisted, then chosen by RUNNING it: a name on PATH that is not a working
# interpreter is the same problem here as the Microsoft Store stub on Windows.
PY=""
for cand in python3 python py; do
  if command -v "$cand" >/dev/null 2>&1 &&
     "$cand" -c "import sys" >/dev/null 2>&1; then
    PY="$cand"
    break
  fi
done
if [ -z "$PY" ]; then
  echo "memory-view: no working Python found (tried: python3, python, py)." >&2
  echo "memory-view: graph-view.html beside this file is a BOOTSTRAP and holds no" >&2
  echo "memory-view: records; it fills itself from this viewer once it runs." >&2
  exit 2
fi

if [ ! -f "$HERE/memory_views.py" ]; then
  echo "memory-view: memory_views.py is not beside this launcher." >&2
  echo "memory-view: this store carries its own viewer so the" >&2
  echo "memory-view: repository works when cloned alone. Restore it with:" >&2
  echo "memory-view:   memory_views.py install --store \"$HERE\"" >&2
  exit 2
fi
# Refresh this store before serving it, WHEN AN ENGINE IS
# REACHABLE: the store itself first, so a genuinely self-contained
# store wins, then a BOUNDED five-level walk UP for an
# orchestration `scripts/` folder. A fixed `../../` would be right
# only where the product sits directly at <container>/main; one
# level deeper it misses, and misses in silence.
ENGINE=""
if [ -f "$HERE/memory_graph.py" ]; then
  ENGINE="$HERE/memory_graph.py"
else
  C="$HERE"
  for _ in 1 2 3 4 5; do
    C=$(dirname "$C")
    if [ -f "$C/scripts/memory_graph.py" ]; then
      ENGINE="$C/scripts/memory_graph.py"
      break
    fi
  done
fi
if [ -n "$ENGINE" ]; then
  "$PY" "$ENGINE" refresh --store "$HERE" --root "$HERE/.." \
      >/dev/null 2>&1 || true
else
  # An unrefreshed map served in silence is believed. Say so.
  "$PY" "$HERE/memory_views.py" engine-missing --store "$HERE" >&2 || true
fi
exec "$PY" "$HERE/memory_views.py" serve --store "$HERE" --open-browser "$@"
