@echo off
REM coverage-view.cmd - open THIS repository's test-coverage map.
REM
REM THIS is the file to click on Windows. coverage-view.sh beside it is the same
REM launcher for Linux and macOS; Windows has no execute association for .sh,
REM so clicking that one only offers to open it in an editor.
REM
REM WHY A SERVER AND NOT JUST THE HTML: coverage-view.html beside this file is a
REM BOOTSTRAP. It holds no records. A page opened straight off disk is a
REM file:// page, and browsers forbid those from reading local files, so it
REM cannot read the test sources or the declarations under testing/. Served over loopback, the same page is rebuilt on
REM every request and reloads itself when its source changes.
REM
REM IT CLEANS UP AFTER ITSELF: closing the last viewer tab stops the server.
REM IT KEEPS TO ITSELF: its port is derived from this repository's own path,
REM it serves only this one, and it never looks for or talks to another.
REM
REM GENERATED by `coverage_views.py install`. Wired to the repository beside it.
setlocal EnableDelayedExpansion
set "HERE=%~dp0"
set "HERE=%HERE:~0,-1%"

REM Pick an interpreter by RUNNING it, never by asking `where`: `python` on
REM Windows may be the Microsoft Store ALIAS STUB, a real file on PATH that is
REM not Python. It prints an advert and exits. `where` says yes and execution
REM says no, and only the second answer is worth having.
set "PY="
py -3 -c "import sys" >nul 2>&1 && set "PY=py -3"
if not defined PY python -c "import sys" >nul 2>&1 && set "PY=python"
if not defined PY (
  echo coverage-view: no working Python found ^(tried: py -3, python^).
  echo coverage-view: coverage-view.html beside this file is a BOOTSTRAP and holds no
  echo coverage-view: records: it fills itself from this viewer once the viewer
  echo coverage-view: runs. Without Python there is nothing to read yet.
  pause
  exit /b 2
)

if not exist "%HERE%\coverage_views.py" (
  echo coverage-view: coverage_views.py is not beside this launcher.
  echo coverage-view: this repository carries its own viewer so the repository
  echo coverage-view: works when cloned alone; without it there is nothing to
  echo coverage-view: serve. Restore it with:
  echo coverage-view:   coverage_views.py install --project "%HERE%\.."
  echo coverage-view: run from a tree that still has one.
  pause
  exit /b 2
)

%PY% "%HERE%\coverage_views.py" serve --project "%HERE%\.." --open-browser %*
REM A .cmd double-clicked from Explorer closes its window the instant the
REM script ends, so a named exit nobody can read is the same as no message at
REM all. This is where the exhausted-port-block message lands.
if errorlevel 1 pause
endlocal
