#!/bin/sh
# coverage-view.sh - open THIS repository's test-coverage map.
#
# The same launcher as coverage-view.cmd, for Linux and macOS.
#
# WHY A SERVER AND NOT JUST THE HTML: coverage-view.html beside this file is a BOOTSTRAP.
# It holds no records. A page opened straight off disk is a file:// page, and
# browsers forbid those from reading local files, so it cannot read the test sources or the declarations under testing/.
#
# IT CLEANS UP AFTER ITSELF: closing the last viewer tab stops the server.
# IT KEEPS TO ITSELF: its port is derived from this repository's own path, it
# serves only this one, and it never looks for or talks to another.
#
# GENERATED by `coverage_views.py install`. Wired to the repository beside it.
set -eu
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# Shortlisted, then chosen by RUNNING it: a name on PATH that is not a working
# interpreter is the same problem here as the Microsoft Store stub on Windows.
PY=""
for cand in python3 python py; do
  if command -v "$cand" >/dev/null 2>&1 &&
     "$cand" -c "import sys" >/dev/null 2>&1; then
    PY="$cand"
    break
  fi
done
if [ -z "$PY" ]; then
  echo "coverage-view: no working Python found (tried: python3, python, py)." >&2
  echo "coverage-view: coverage-view.html beside this file is a BOOTSTRAP and holds no" >&2
  echo "coverage-view: records; it fills itself from this viewer once it runs." >&2
  exit 2
fi

if [ ! -f "$HERE/coverage_views.py" ]; then
  echo "coverage-view: coverage_views.py is not beside this launcher." >&2
  echo "coverage-view: this repository carries its own viewer so the" >&2
  echo "coverage-view: repository works when cloned alone. Restore it with:" >&2
  echo "coverage-view:   coverage_views.py install --project \"$HERE/..\"" >&2
  exit 2
fi

exec "$PY" "$HERE/coverage_views.py" serve --project "$HERE/.." --open-browser "$@"
